### ISSUE TITLE
v2.0.1 :: "HTTP Response Error" for valid responses

### ISSUE THREAD

**Issue by yoosefi** [mivaecommerce/api-sdk-php#1] opened 2022-03-29 21:00 UTC
v2.0.1 introduced a regression

https://github.com/mivaecommerce/api-sdk-php/blob/7b61091e16cf85f7c9c351354866234f1af7b3c3/src/BaseClient.php#L286-L288

this change broke the method because `$httpResponse->getStatus()` is returning `null` for valid responses. the sdk now throws `ClientException` for every request.

this broke our installation and i've downgraded to `v2.0.0` to resolve it. please use semantic versioning and do not add new features for a patch-version. https://semver.org/

**Comment by ghassani** [comment] 2022-03-29 22:26
Unable to reproduce this on nginx or apache. Could be a possible issue with HttpResponse::receiveHeaderCallback parsing the status code, might be a configuration issue on the web server. Can you provide a response capture from your setup?

**Comment by ghassani** [comment] 2022-03-30 21:14
I found the issue. It only parses the response status line if it is in the format HTTP/X.X. So there are cases where this will fail, for example if the web server is using http2. 

Should be fixed in the next release.

Reference: MMAPI-55

**Comment by yoosefi** [comment] 2022-03-31 07:11
@ghassani i confirmed HTTP/2 is in use in this scenario, yes.

**Comment by ghassani** [comment] 2022-04-05 19:40
Fixed in 2.1.0

**Closed as completed by ghassani** 2022-04-05 19:40 UTC
